### ISSUE TITLE
SVG tags renderization

### ISSUE THREAD

**Issue by jonatasnardi** [Novaleaf/phantomjscloud-node-examples#2]
Hello! 

When I get the screenshot from this page https://assine.vivo.com.br/CURITIBA_PR/ , we can see that SVGs doesn't render correctly. It has a solution? 

Screenshot: http://i.imgur.com/RfBZlWrg.jpg

Thanks ;)

**Comment by jasonswearingen** [comment]
hi, sorry this looks to most likely be because of PhantomJs's outdated rendering.  I don't think there's anything we can do about it at this time.   FYI we are building a new backend that uses Electron (instead of PhantomJs) but that won't be ready for the public until the new year.   I'll send an announcment mail when it's ready for public use.

**Comment by jonatasnardi** [comment]
Oh, anyway, thanks a lot!
That issue happens only with use the tag `<svg>`. I really needed that works :(

Thanks man! =)

**Comment by jasonswearingen** [comment]
hi, FYI we have the phantomjs 2.5 beta installed, so you can try that, in case it renders better. 

for example:

```
{
	pages:[
		{"url":"https://example.com/",
                    "renderType":"jpeg",
		}
		],backend:"beta",
}
```

however there are a lot of bugs in 2.5beta so again, you might need to wait for our chrome based render.
